# to get ansible_os_family type ansible localhost -m setup in command line
---
- name: Install Apache Webserver
  hosts: localhost
  become: yes

  tasks:
    - name: Install apache on ubuntu server
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
  
    - name: Install apache2 on centos server
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
