---
- name: Enable service on firewalld
  hosts: all
  become: yes

  tasks:

  - name: Install httpd
    yum:
      name: httpd
      state: latest 
    notify:
    - restart httpd

  - name: Open port for http
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:
    - restart httpd


  - name: Ensure firewalld is running
    service:
       name: firewalld
       state: started


  handlers:
    - name: Reload firewalld
      service:
        name: httpd
        state: restarted
      listen: "restart httpd"
