---
- name: setup apache server
  hosts: all
  become: yes

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    tags: i-httpd

  - name: start httpd
    service:
      name: httpd
      state: started
    tags: s-httpd
 
