---
- name: Download tomcat from tomcat.apache.org
  hosts: localhost
  become: yes

  tasks:
  - name: Create a directory
    file:
       path: /opt/tomcat
       state: directory
       mode: 0755
       owner: root
       group: root
  - name: Download Tomcat using get_url
    get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
       dest: /opt/tomcat
       group: ubuntu
       owner: ubuntu
