---
- name: Install httpd package
  yum:
    name: httpd
    state: present

- name: Start httpd
  service:
    name: httpd
    state: started

- name: open port for http
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: restart firewalld
  service:
    name: firewalld
    state: reloaded
